pipeline {
    agent {
        label 'devops'
    } 
    
    stages{
        stage("Clone Code"){
            steps {
                echo "Cloning the code"
                git branch: 'main', url: 'https://github.com/tarunp2912/jenkins-test.git'
            }
        }

        stage("Build"){
            steps {
                echo "Building the image"
                sh "docker build -t phpweb ."
            }
        }

        // stage("Push to Docker Hub"){
        //     steps {
        //         echo "Pushing the image to docker hub"
        //         withCredentials([usernamePassword(credentialsId:"dockerHub",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
        //         sh "docker tag my-note-app ${env.dockerHubUser}/my-note-app:latest"
        //         sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
        //         sh "docker push ${env.dockerHubUser}/my-note-app:latest"
        //         }
        //     }
        // }
        
        stage("Deploy"){
            steps {
                echo "Deploying the container"
                sh "docker run -dit --name webserver -p 80:80 phpweb:latest"
                
            }
        }
    }
}